### ISSUE TITLE
Tracking issues of List Builder

### ISSUE THREAD

**Issue by Xuanwo** [rewrite-bigdata-in-rust/RBIR#16]
This is a tracking issue for List Builder. This issue want to make it easier to maintain the RBIR lists support all the features we want:

- https://github.com/rewrite-bigdata-in-rust/RBIR/issues/13
- https://github.com/rewrite-bigdata-in-rust/RBIR/issues/15
- https://github.com/rewrite-bigdata-in-rust/RBIR/issues/4

The basic idea is to build a rust cli that can read project/lib/posts list and fetch metadata we want to build a easy to use list.

## Tasks

- [x] Generate new README with extracted `projects.toml`, `libraries.toml`, `posts.toml`
- [ ] Fetch more metadata about project: star, issues, prs, good first issues.
- [ ] Provide more context for projects: depends on, uses..
